### PR TITLE
Fix/a11y registration

### PR DESCRIPTION
**Pull request by iamtomhanks**
#### Summary
Addressed a11y changes recommended by Ari, in the /Registration tab, in the following document:

https://docs.google.com/spreadsheets/d/1ZSilJkhbqsjjJi0BC-wJvI1AVXedFIE5S8vNbUJMtxI/edit#gid=157159830

Changes were initially applied to /signup_email, then additionally added to /signup_lti

#### Ticket Link
https://trello.com/b/OFWhBnfw/riff?menu=filter&filter=member:brechanson

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Has UI changes

### CODE REVIEW

**Comment by iamtomhanks** [comment]
[a11y - Registration](https://trello.com/c/yA4lEMjs/287-a11y-registration)

**Comment by mlippert** [comment]
force pushed to rebase to head of develop for review (and to see how new CI works)

**Comment by mlippert** [comment]
force pushed to current head of develop for review (eventually, I'm not ready to start reviewing just yet)

**Comment by adonahue** [comment]
@mlippert - it looks like this story is in play, and waiting a code review by you - am I understanding that correctly?

**Comment by mlippert** [comment]
@adonahue Yes that is correct.

**Comment by adonahue** [comment]
thanks @mlippert . I moved to in progress, and realized I'm not sure how we should go about estimating / accounting for small pieces of work like code reviews or small bugs. I stuck a 1 on this story since it's our smallest unit, but I'm guessing this is not a full day's worth of work, right?

**Comment by mlippert** [comment]
I'm anticipating this review needing more time than usual (which is why I haven't tackled it yet) because it's modifying the work done by BrightScout which adhered more closely to the practices of the main mattermost codebase, and I want to ensure that the changes here, continue to do that.

**Comment by juliariffgit** [comment]
Holding off for right now. At this time, still on track for this sprint, but needs a closer look.

**Comment by mlippert** [comment]
force pushed to the head of develop

**Comment by adonahue** [comment]
@mlippert - what's the status of this story? I'd like to close it out, but I'm not sure what work / steps are remaining. Thx!

**Comment by mlippert** [comment]
This is in rifflearning/mattermost-webapp [`1.0.0-dev.30`](https://github.com/rifflearning/mattermost-webapp/tree/1.0.0-dev.30) which was in the edu-mm version `1.0.0-dev.14` which was just deployed to staging.riffedu.com

**Comment by adonahue** [comment]
@brecriffs - I went through and marked the spreadsheet tab above. All the green rows look good. The orange and yellow rows are not passing as best I can tell. I think row 8 is also related to the aria stuff. I'm a little out of my element in the a11y testing....Can you take a look and see if these need to be addressed? Thanks!

**Pull request merged**
