### PR TITLE
fix theme contrast & switchability

### PR DESCRIPTION
**Pull request by arizzitano**
#### Summary
Fix the contrast and redisplay issues with prior PR #29.

#### Ticket Link
https://trello.com/c/sFKOriuh/223-high-contrast-theme-for-riff-edu

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Needs to be implemented in mobile (link to PR or User Story)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [X] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by arizzitano** [comment]
FYI @mlippert there is a bit of whitespace noise here since I fixed some of the existing eslint style issues in `needs-theme.jsx`. `utils.jsx` contained a large number of warnings, but no errors.

**Comment by mlippert** [comment]
[High contrast theme for Riff Edu](https://trello.com/c/sFKOriuh/223-high-contrast-theme-for-riff-edu)

**Comment by mlippert** [comment]
rebased to head of develop (which moved after this PR was opened, because other PRs have been merged)

**Comment by mlippert** [comment]
Thanks Ari, we're definitely making progress on the style errors!

**Comment by mlippert** [comment]
Copying the Trello card comments here because Trello is a pain to access, and as this is part of the Riff modifications we move from one Mattermost release to the next it's good to have as much of the original discussion about the change as I can find.

## Story description
As a user, I want a theme in Riff Edu that meets WCAG 2.0 AA contrast standards.

As a PM, I would like our default, Riff Branded theme (in Riff colors) to meet contrast standards so everyone benefits. If this is difficult to do in the product platform, it is also ok to have a second (high contrast) themein the product that users can easily apply via their theme settings.

This PR and #29 were attached to the story. There are some gifs and mp4's attached to the Trello story that I am not copying here.

## Comments
Amy Donahue Feb 12, 2019 at 6:11 AM

>@arizzitano - I'm seeing contrast errors in AXE, mostly on the left nav, and body text. Also, it looks like when a new theme is applied there's some sort of glitch where it doesn't fully render across teams, until you click into a channel. I'll attach some images.

Ari Rizzitano Feb 12, 2019 at 11:30 PM

>@amy_d I addressed the following issues you brought up, which were legitimate contrast failures:
>- Increased contrast in left-hand number badge for multi-user DMs
>- Increased contrast in all channel header buttons at the top of the screen
>- Increased contrast in channel body text announcing who has entered or left a channel
>
>Axe will still throw contrast errors ("we are not sure if this is an issue") if it's not sure whether an element passes contrast checks, but this doesn't necessarily mean they fail. In your attached video, this happens for the channel intro, "joined the team" body text, and the attachment paperclip icon. I hand-examined the contrast for all of these elements and all of them pass, but I increased the contrast of the paperclip just to be safe. Attached is a video showing these "uncertain" Axe issues -- none are actually a problem.
>
>I also fixed the issue with the theme not displaying properly when in-between teams (gif attached below). The PR rifflearning/mattermost-webapp: Pull Request 42 is up and ready for review.

**Pull request merged**
