### PR TITLE
Fix/a11y dashboard

### PR DESCRIPTION
**Pull request by iamtomhanks**
#### Summary
Addressed all of the a11y notes for the Dashboard.

Each commit has details.

#### Ticket Link
https://trello.com/c/MkIkKBQS/283-a11y-dashboard

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Has UI changes

### CODE REVIEW

**Comment by iamtomhanks** [comment]
[a11y - Dashboard](https://trello.com/c/MkIkKBQS/283-a11y-dashboard)

**Comment by iamtomhanks** [comment]
[a11y - Dashboard](https://trello.com/c/MkIkKBQS/283-a11y-dashboard)

**Comment by iamtomhanks** [comment]
[a11y - Dashboard](https://trello.com/c/MkIkKBQS/283-a11y-dashboard)

**Comment by mlippert** [comment]
force pushed to head of develop (resolved 1 minor conflict)

**Comment by mlippert** [comment]
@iamtomhanks I put back the comment you had added and removed about why the setTimeout was needed. I found it quite helpful when I was initially reading the code.

I also added PropTypes to the new ChartInfoDiv because I thought it might be straight forward (it was) mostly as a test of how to do it going forward (eventually).

**Pull request merged**
