### PR TITLE
Enable all passing mattermost tests

### PR DESCRIPTION
**Pull request by jaedoucette**
#### Summary

Failing tests can now be re-enabled by removing the ignore rule in `package.json` for `/failing_tests/`.

Note: does not address tests that fail to run entirely (there are 11 of these).

### CODE REVIEW

**Comment by jaedoucette** [comment]
Note: The Mattermost tests have several thousand style errors within them. I was not sure whether we preferred to disable check-style for the tests, or to increase the maximum number of errors required for a build to be considered "passing".

**Comment by mlippert** [comment]
@jaedoucette That's not what I saw when I ran check-style.
The number of style errors went from 51 to 78, and all the new errors are in 12 test files and almost all of them are `no-unused-vars` errors, probably related to having tests removed or commented out?

**Comment by jaedoucette** [comment]
@mlippert We talked about the `check-style` issue a bit today. When I run `make check-style` on the new branch you made, I also get 2929 style errors.

Turns out this is caused by the results of the output of the `make coverage` target, which generates a large number of files with the `.js` extension. I pushed a commit to your new branch adding `coverage` to the ignored directories for `eslint`.

**Comment by mlippert** [comment]
The force push was for re-organizing the commits in this PR. The re-organization was done in conjunction with @jaedoucette.

The intent is to have a very clean organized progression of changes to enabling all of the passing mattermost tests that had been disabled, and to moving all of the failing tests aside so they are ignored for now, but can easily be run by editing the `testPathIgnorePatterns` section in package.json.

There are now 1323 passing tests. And all of these tests are run by the gitlab CI.

```
Test Suites: 216 passed, 216 total
Tests:       15 skipped, 1323 passed, 1338 total
Snapshots:   584 passed, 584 total
Time:        24.586s
Ran all test suites.
```

**Pull request merged**
